AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template for Aurora PostgreSQL RDS Cluster across environments'

Parameters:
  Environment:
    Type: String
    Description: Environment type
    AllowedValues:
      - dev
      - qa
      - prod
    Default: dev

  DBName:
    Type: String
    Description: Database name
    Default: mydb
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'

  DBUsername:
    Type: String
    Description: Database admin username
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'

  DBPassword:
    Type: String
    Description: Database admin password
    NoEcho: true
    MinLength: '8'
    MaxLength: '41'

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs for the DB Subnet Group

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']
  IsQA: !Equals [!Ref Environment, 'qa']
  IsDev: !Equals [!Ref Environment, 'dev']

Mappings:
  EnvironmentConfig:
    dev:
      instanceClass: db.t3.medium
      multiAZ: false
      storageSize: 20
      maxStorageSize: 100
      backupRetention: 7
    qa:
      instanceClass: db.t3.medium
      multiAZ: false
      storageSize: 50
      maxStorageSize: 200
      backupRetention: 14
    prod:
      instanceClass: db.r5.large
      multiAZ: true
      storageSize: 100
      maxStorageSize: 500
      backupRetention: 35

Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub 'Allow database access - ${Environment}'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !If 
            - IsProd
            - '10.0.0.0/8'  # Restricted IP range for prod
            - '0.0.0.0/0'   # More permissive for non-prod
      Tags:
        - Key: Environment
          Value: !Ref Environment

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub 'Subnet group for RDS - ${Environment}'
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Environment
          Value: !Ref Environment

  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: 16.6
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      BackupRetentionPeriod: !FindInMap [EnvironmentConfig, !Ref Environment, backupRetention]
      VpcSecurityGroupIds:
        - !GetAtt RDSSecurityGroup.GroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeletionProtection: !If [IsProd, true, false]
      StorageEncrypted: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: MyApp

Outputs:
  RDSEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt AuroraDBCluster.Endpoint.Address

  RDSPort:
    Description: RDS instance port
    Value: !GetAtt AuroraDBCluster.Endpoint.Port

  DBName:
    Description: Database name
    Value: !Sub '${DBName}_${Environment}'

  Environment:
    Description: Deployment Environment
    Value: !Ref Environment
