name: Deploy to DEV/QA AWS

on:
  push:
    branches:
      - develop
# Add this permissions block
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

#DEV deployment
      - name: Configure AWS Credentials (Dev)
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_DEV }}
          aws-region: us-east-1
          role-session-name: GitHubActions
          audience: sts.amazonaws.com

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/develop'
        run: |
          aws s3 ls

#QA deployment
      - name: Configure AWS Credentials (QA)
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_QA }}
          aws-region: us-east-1
          role-session-name: GitHubActions
          audience: sts.amazonaws.com

      - name: Deploy to QA
        if: github.ref == 'refs/heads/develop'
        run: |
          aws s3 ls
